Reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :users, only: [:new, :create, :index, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :subs, except: [:destroy]
end

Reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
    
end

Reddit_clone/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
class User < ApplicationRecord

    attr_reader :password

    validates :username, :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 6}, allow_nil: true
    validates :password_digest, presence: true 
    before_validation :ensure_session_token

    def generate_session_token
        SecureRandom::urlsafe_base64
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end

    def self.find_by_creds(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user 
        else 
            nil
        end
    end

    def is_password?(new_pass)
        obj = BCrypt::Password.new(self.password_digest)
        obj.is_password?(new_pass)
    end

    def password=(new_pass)
        self.password_digest = BCrypt::Password.create(new_pass)
        @password = new_pass
    end

    def reset_session_token!
        self.session_token = generate_session_token
        self.save!
        self.session_token
    end

end

Reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    helper_method :current_user, :logged_in?

    def current_user
        @current_user = User.find_by(session_token: session[:session_token])
    end

    def log_in(user)
        session[:session_token] = user.reset_session_token!
    end

    def logged_in?
        !!current_user
    end

    def log_out!
        current_user.reset_session_token! if logged_in?
        session[:session_token] = nil
        @current_user = nil
    end

    def require_logged_in
        redirect_to new_session_url if !logged_in?
    end

    def require_logged_out
        redirect_to users_url if logged_in?
    end

end

Reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        @user = User.new
        render :new
    end

    def create
        # debugger
        @user = User.find_by_creds(params[:user][:username], params[:user][:password])
        if @user
            log_in(@user)
            redirect_to user_url(@user)
        else
            @user = User.new(
                username: params[:user][:username],
                password: params[:user][:password]
            )
            render :new
        end
    end

    def destroy
        if logged_in?
            log_out!
        end
        flash[:message] = ["Successfully logged out"]
        redirect_to new_session_url
    end
end

        

Reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    def edit
        
    end
end

Reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all 
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
        if @user
            render :show
        else
            redirect_to new_user_url
        end
    end

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            log_in(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end

end

Reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

Reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

Reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

Reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>
    <h1>RedditClone</h1>
  <body>
    <nav>
      <% if logged_in? %>
      <form action="<%= session_url%>" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE"/>
        <input type="submit" value="Log Out"/>
      </form>
      <% else %>
        <a href="<%= new_user_url%>">Sign Up</a>
        <br>
        <a href="<%= new_session_url%>">Log In</a>
      <% end %>  
    </nav>
    <%= yield %>
  </body>
</html>

 

Reddit_clone/app/views/session/new.html.erb
<h1>Log In</h1>

<form action="<%= session_url %>" mehtod="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <label for="username"> Username: 
        <input type="Text" name="user[username]" value="<%= @user.username %>">
    </label> 
    <br>
    <label for="password"> Password:
        <input type="Password" name="user[password]" value="">
    </label>
    <br>
    <input type="submit" value="Log In">

</form>

Reddit_clone/app/views/users/index.html.erb
<h1>All Users</h1>
<% @users.each do |user| %>
    <ul>
        <li><%= user.username %></li>
    </ul>
<% end %>

Reddit_clone/app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
    <label for="username"> Username: 
        <input type="Text" name="user[username]" value="<%= @user.username %>">
    </label> 
    <br>
    <label for="password"> Password:
        <input type="Password" name="user[password]" value="">
    </label>
    <br>
    <input type="submit" value="Sign Up">

</form>

Reddit_clone/app/views/users/show.html.erb
<h1>Welcome <%=@user.username%></h1>